### ISSUE TITLE
Not deploying in latest master

### ISSUE THREAD

**Issue by jordirodo** [yasuflatland-lf/liferay-dummy-factory#10]
Error on deploy in latest master:

```
08:56:33,740 ERROR [Framework Event Dispatcher: Equinox Container: d0a2cd32-9897-0017-1c0c-e215f8aa209e][liferay_dummy_factory:97] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: liferay.dummy.factory [648]_  Unresolved requirement: Import-Package: com.liferay.journal.model; version="[1.0.0,2.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:429)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

**Comment by rodrigopaulino** [comment]
Hey, guys!

I've tried to deploy, on latest master and latest 7.0.x, both .zip posted on Loop and .jar posted here. Nothing works, but instead of @jordirodo's log nothing shows on my console. :/
Is there any updates on this?

Thanks.

**Comment by rodrigopaulino** [comment]
Actually the same thing happened to me. I could see the same OSGi exception when I restarted the Tomcat.

**Comment by yasuflatland-lf** [comment]
@jordirodo , @rodrigopaulino , I just made sure the deployment worked against liferay-portal/7.0.x branch. Please check it out and reopen this if it still doesn't work.
