### ISSUE TITLE
Unresolved requirement when deploying in latest master

### ISSUE THREAD

**Issue by brookedalton** [yasuflatland-lf/liferay-dummy-factory#35]
Hello, I'm seeing this error when deploying the jar file in the bundle on the latest liferay master. Does it only work with published versions?
```
2020-07-10 00:07:35.591 ERROR [fileinstall-/Documents/master/bundles/osgi/modules][LogService:93] Error while starting bundle: file:/Documents/master/bundles/osgi/modules/liferay.dummy.factory-7.3.0.jar
org.osgi.framework.BundleException: Could not resolve module: liferay.dummy.factory [1083]
  Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.model; version="[3.1.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1297)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1270)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:524)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:369)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:320)
```
Thanks!

**Comment by yasuflatland-lf** [comment]
@brookedalton Thank you for reporting this. Yeah, looks like it. You may be able to build on your own, but the concern is if BOM for the master are available in public, maybe not. In that case, you may need to deeply the BOM and dependency jars at local and pointing them.
