### ISSUE TITLE
At creating a company, the exception below is thrown.

### ISSUE THREAD

**Issue by yasuflatland-lf** [yasuflatland-lf/liferay-dummy-factory#36]
At creating a company, the exception below is thrown.

> 2020-11-16 05:59:46.821 ERROR [http-nio-8080-exec-6][IncludeTag:128] Current URL /group/control_panel/manage?p_p_id=com_liferay_support_tools_portlet_LiferayDummyFactoryPortlet&p_p_lifecycle=1&p_p_state=maximized&p_p_mode=view&_com_liferay_support_tools_portlet_LiferayDummyFactoryPortlet_javax.portlet.action=%2Fldf%2Fcompany&_com_liferay_support_tools_portlet_LiferayDummyFactoryPortlet_mode=COMPANY&_com_liferay_support_tools_portlet_LiferayDummyFactoryPortlet_redirect=http%3A%2F%2Flocalhost%3A8080%2Fgroup%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_support_tools_portlet_LiferayDummyFactoryPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview generates exception: null
java.lang.NullPointerException
	at com.liferay.layout.seo.internal.util.FriendlyURLMapperProvider.getFriendlyURLMapper(FriendlyURLMapperProvider.java:54)
	at com.liferay.layout.seo.internal.canonical.url.LayoutSEOCanonicalURLProviderImpl._getDefaultCanonicalURL(LayoutSEOCanonicalURLProviderImpl.java:136)
	at com.liferay.layout.seo.internal.canonical.url.LayoutSEOCanonicalURLProviderImpl.getCanonicalURL(LayoutSEOCanonicalURLProviderImpl.java:67)
	at com.liferay.layout.seo.internal.LayoutSEOLinkManagerImpl.getCanonicalLayoutSEOLink(LayoutSEOLinkManagerImpl.java:63)
	at org.apache.jsp.html.common.themes.top_005fhead_jsp._jspService(top_005fhead_jsp.java:1277)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64)
	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
	at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:407)
	at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:383)
	at com.liferay.taglib.util.IncludeTag.doInclude(IncludeTag.java:217)
	at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:88)
	at freemarker.ext.jsp.TagTransformModel$TagWriter.endEvaluation(TagTransformModel.java:402)
	at freemarker.ext.jsp.TagTransformModel$TagWriter.afterBody(TagTransformModel.java:390)
	at freemarker.core.Environment.visitAndTransform(Environment.java:497)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:103)
	at freemarker.core.Environment.visit(Environment.java:331)

**Comment by yasuflatland-lf** [comment]
DXP 2026.Q1.3-LTS への 2.0 rewrite (PR #53) により、該当コードパス（旧 Company 作成フロー）は全面的に置き換えられました。現行の React + BatchResult<T> 実装では再現しないため、not planned でクローズします。
