### ISSUE TITLE
Adding Dummy Factory to a page throws No tag "upload-progress" defined in tag library imported with prefix "liferay-ui" 

### ISSUE THREAD

**Issue by lipusz** [yasuflatland-lf/liferay-dummy-factory#49]
Hi Yasu,

When I'm adding the [latest version](https://github.com/yasuflatland-lf/liferay-dummy-factory/tree/master/latest) (`7.4.4`) of the module to a page on master (`liferay-portal@eb99c8776afffd89a16b77f023ba1641e1d852cc` ~U112), latest HEAD today) it is generating the following error:

```
2024-02-13 10:37:13.492 ERROR [http-nio-8080-exec-7][PortletRequestDispatcherImpl:295] Unable to dispatch request: /view.jsp(123,16) PWC6142: No tag "upload-progress" defined in tag library imported with prefix "liferay-ui"
2024-02-13 10:37:13.493 ERROR [http-nio-8080-exec-7][PortletServlet:109] Unable to process portlet com_liferay_support_tools_portlet_LiferayDummyFactoryPortlet: org.apache.jasper.JasperException: /view.jsp(123,16) PWC6142: No tag "upload-progress" defined in tag library imported with prefix "liferay-ui"
javax.portlet.PortletException: org.apache.jasper.JasperException: /view.jsp(123,16) PWC6142: No tag "upload-progress" defined in tag library imported with prefix "liferay-ui"
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:298) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:114) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:611) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:627) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doView(MVCPortlet.java:172) ~[portal-kernel.jar:?]
	at com.liferay.support.tools.portlet.LiferayDummyFactoryPortlet.doView(LiferayDummyFactoryPortlet.java:70)
```

Thanks for looking into this. :blue_heart: 

Regards,
Tibor

**Comment by sorin-pop** [comment]
I have the same issue.

**Comment by yasuflatland-lf** [comment]
@sorin-pop @lipusz Should be resolved issue. I decided to release versions according to quarterly release convention. See the branch name match to the quarterly release.
